import pandas as pd
import plotly.io as pio


def generate_html_report(test_metadata, stats, derived, figures, notes=""):
    """
    Generates a standalone HTML file containing metrics and interactive Plotly figures.

    Args:
        test_metadata (dict): {'Filename': '...', 'Config': '...', 'Date': '...'}
        stats (dict): The main averaged statistics (Pressure, Thrust, etc.)
        derived (dict): Calculated efficiencies (Isp, Cd, etc.)
        figures (list): List of Plotly Figure objects to embed.
        notes (str): User comments.
    """

    # 1. Convert Figures to HTML strings (divs)
    # include_plotlyjs='cdn' keeps the file size small (loads lib from web)
    # or 'True' to make it fully offline (larger file ~3MB)
    fig_htmls = ""
    for i, fig in enumerate(figures):
        fig_htmls += f'<div class="chart-container">{pio.to_html(fig, full_html=False, include_plotlyjs="cdn")}</div>'

    # 2. Format Metrics Table
    # We'll split stats and derived into two columns for layout
    stats_rows = "".join([f"<tr><td>{k}</td><td>{v}</td></tr>" for k, v in stats.items()])
    derived_rows = "".join([f"<tr><td>{k}</td><td>{v}</td></tr>" for k, v in derived.items()])

    # 3. The HTML Template
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>Test Report: {test_metadata.get('Filename')}</title>
        <style>
            body {{ font-family: 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; margin: 40px; background: #f4f4f9; color: #333; }}
            .header {{ background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 5px rgba(0,0,0,0.05); margin-bottom: 20px; }}
            .header h1 {{ margin: 0; color: #2c3e50; }}
            .meta {{ color: #7f8c8d; font-size: 0.9em; margin-top: 5px; }}

            .grid-container {{ display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 20px; }}
            .card {{ background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 5px rgba(0,0,0,0.05); }}
            h2 {{ border-bottom: 2px solid #ecf0f1; padding-bottom: 10px; margin-top: 0; font-size: 1.2em; color: #34495e; }}

            table {{ width: 100%; border-collapse: collapse; }}
            td {{ padding: 8px; border-bottom: 1px solid #eee; }}
            td:first-child {{ font-weight: 600; color: #555; width: 60%; }}
            td:last-child {{ font-family: monospace; font-size: 1.1em; color: #2980b9; }}

            .chart-container {{ background: white; padding: 10px; border-radius: 8px; box-shadow: 0 2px 5px rgba(0,0,0,0.05); margin-bottom: 20px; }}
            .notes {{ background: #fff3cd; color: #856404; padding: 15px; border-radius: 8px; border: 1px solid #ffeeba; margin-bottom: 20px; }}

            @media print {{
                body {{ background: white; margin: 0; }}
                .card, .header, .chart-container {{ box-shadow: none; border: 1px solid #ddd; }}
                .no-print {{ display: none; }}
            }}
        </style>
    </head>
    <body>
        <div class="header">
            <h1> Test Analysis Report</h1>
            <div class="meta">
                File: {test_metadata.get('Filename')} | 
                Config: {test_metadata.get('Config')} | 
                Date: {pd.Timestamp.now().strftime('%Y-%m-%d %H:%M')}
            </div>
        </div>

        {f'<div class="notes"><strong> Notes:</strong> {notes}</div>' if notes else ''}

        <div class="grid-container">
            <div class="card">
                <h2> Primary Statistics</h2>
                <table>{stats_rows}</table>
            </div>
            <div class="card">
                <h2> Performance Metrics</h2>
                <table>{derived_rows}</table>
            </div>
        </div>

        {fig_htmls}

        <div style="text-align: center; margin-top: 40px; color: #aaa; font-size: 0.8em;">
            Generated by Hopper Data Studio
        </div>
    </body>
    </html>
    """

    return html_content.encode('utf-8')